version: '3.8'

name: eleven_sp
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=eleven_sp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
